twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    #form_themes: ['bootstrap_4_Horizontal_layout.html.twig']
    globals:
        appName: 'Nissim'
        appConcepteur: "HL Consulting"

when@test:
    twig:
        strict_variables: true
