vich_uploader:
    db_driver: orm

    mappings:
        projets:
            uri_prefix: /uploads/images/projects
            upload_destination: '%kernel.project_dir%/public/uploads/images/projects'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
